name: "Tests"

on:
  push:
    paths:
      - ".github/**/*"
      - "lua/*"
      - "lua/**/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - run: sudo apt-get update && sudo apt-get install -y libreadline-dev
      - uses: jdx/mise-action@v2
        with:
          tool_versions: |
            lua 5.1
      - run: luarocks --lua-version=5.1 install vusted
      - run: /home/runner/.local/share/mise/installs/lua/5.1/luarocks/bin/vusted lua
